// Package internal collects and registers all the available games this
// Joueur client can play.
// NOTE: modifying the impl data for any game(s) could probably break gameplay,
// or break the build. All files outside this are generated by the Creer
// code geneation tool and should not be changed unless you know what you are
// doing.
package internal

import "joueur/base"

var GameNamespaceRegistry = make(map[string]base.GameNamespace)

func register(gameName string, gameNamespace base.GameNamespace) {
	GameNamespaceRegistry[gameName] = gameNamespace
}
